const STORAGE='juniper-home-tracker-v2';
const LEGACY='juniper-home-tracker-v1';
const $=id=>document.getElementById(id);
const money=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Math.round(Number(n))):'—';
const pct=n=>`${Number(n)>=0?'+':''}${Number(n||0).toFixed(1)}%`;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const clone=x=>JSON.parse(JSON.stringify(x));
const today=()=>new Date().toISOString().slice(0,10);
const seededSources=[
{id:'zillow',name:'Zillow estimate',value:513000,inBlend:true,url:'https://www.zillow.com/',date:'Oct 2026'},
{id:'redfin',name:'Redfin estimate',value:572390,inBlend:true,url:'https://www.redfin.com/',date:'2026'},
{id:'homes',name:'Homes.com estimate',value:529565,inBlend:true,url:'https://www.homes.com/',date:'Sep 2026'},
{id:'county',name:'County / tax value',value:545980,inBlend:false,url:'',date:'latest record'}];
const seededComps=[
{id:'c1',address:'189 Sioux Trail',salePrice:426366,saleDate:'',sqft:1064,acres:'',beds:2,baths:1,quality:'okay',adjustment:0,use:true,notes:'Prior research example — verify sale date/condition.'},
{id:'c2',address:'509 Paiute Rd',salePrice:535000,saleDate:'',sqft:1459,acres:'',beds:2,baths:2,quality:'strong',adjustment:0,use:true,notes:'Prior research example — useful 2/2 comparison.'},
{id:'c3',address:'150 Cedar Rd',salePrice:575000,saleDate:'',sqft:1305,acres:'',beds:3,baths:3,quality:'okay',adjustment:0,use:true,notes:'Prior research example — more baths/bedrooms.'},
{id:'c4',address:'8 Sioux Trail',salePrice:587500,saleDate:'',sqft:1440,acres:'',beds:3,baths:2,quality:'okay',adjustment:0,use:true,notes:'Prior research example — verify condition.'},
{id:'c5',address:'7520 S Blue Creek Rd',salePrice:515000,saleDate:'',sqft:737,acres:1.65,beds:2,baths:1,quality:'strong',adjustment:0,use:true,notes:'Prior research example — small home / acreage analog.'}];
const seededProjects=[
{id:'punch',name:'Punch list + paint + obvious repairs',tier:'small',score:5,type:'Buyer objection',budget:3000,valueAdd:3000,status:'Idea',actual:0,permit:'No',selected:false,why:'Fix what buyers notice immediately and remove deferred-maintenance friction.'},
{id:'fire',name:'Wildfire mitigation / defensible space',tier:'small',score:5,type:'Protect value',budget:5000,valueAdd:2500,status:'Idea',actual:0,permit:'No',selected:false,why:'Protects insurability, inspection confidence and mountain-property marketability.'},
{id:'deck',name:'Deck repair / refinish / safety',tier:'medium',score:4,type:'Outdoor utility',budget:10000,valueAdd:6000,status:'Idea',actual:0,permit:'Maybe',selected:false,why:'The deck is part of the mountain-living product. Structure and rails first, appearance second.'},
{id:'windows',name:'Strategic windows / envelope',tier:'medium',score:4,type:'Durability',budget:18000,valueAdd:13300,status:'Idea',actual:0,permit:'Maybe',selected:false,why:'Comfort, egress and views can add utility; replace strategically rather than automatically.'},
{id:'kitchen',name:'Kitchen refresh — not luxury gut',tier:'medium',score:4,type:'Buyer appeal',budget:22000,valueAdd:13200,status:'Idea',actual:0,permit:'Maybe',selected:false,why:'Keep a functional layout and spend where buyers see condition and usability.'},
{id:'bath1',name:'Renovate existing bathroom',tier:'medium',score:3,type:'Condition',budget:20000,valueAdd:10000,status:'Idea',actual:0,permit:'Maybe',selected:false,why:'Clean, durable and timeless beats over-improving the only existing bath.'},
{id:'roof',name:'Roof replacement when condition calls',tier:'major',score:5,type:'Protect value',budget:25000,valueAdd:15000,status:'Idea',actual:0,permit:'Yes',selected:false,why:'Condition, insurance and buyer confidence; not a cosmetic profit project.'},
{id:'bath2',name:'Add a legal second bathroom',tier:'major',score:5,type:'Buyer pool',budget:40000,valueAdd:30000,status:'Idea',actual:0,permit:'Yes',selected:false,why:'Can remove a major 2/1 buyer objection and widen search-filter eligibility.'},
{id:'adu',name:'Garage + permitted in-law / ADU conversion',tier:'major',score:5,type:'Legal utility',budget:150000,valueAdd:80000,status:'Idea',actual:0,permit:'Yes',selected:false,why:'Leverage the powered garage and finished/heated loft; documented legal utility matters more than luxury finishes.'}];
const seededRisks=[
{id:'wildfire',name:'Wildfire / defensible space',status:'watch',notes:'Review annually and before insurance renewal.'},
{id:'insurance',name:'Insurance / insurability',status:'watch',notes:'Track carrier requirements and premium changes.'},
{id:'roof',name:'Roof condition',status:'low',notes:'Record age, inspections and replacement planning.'},
{id:'well',name:'Well / water system',status:'low',notes:'Keep service/testing history.'},
{id:'septic',name:'Septic system',status:'low',notes:'Track pumping, inspection and capacity for any ADU work.'},
{id:'deck',name:'Deck / stairs / railings',status:'watch',notes:'Safety and exterior buyer impression.'},
{id:'drainage',name:'Drainage / slope / runoff',status:'watch',notes:'Watch erosion and water movement after storms/snowmelt.'},
{id:'electrical',name:'Electrical / garage power',status:'low',notes:'Garage has useful existing power; document upgrades and permits.'}];
const defaults={
propertyName:'Juniper Home Tracker',privateAddress:'',locationLabel:'Evergreen-area, Colorado',primarySqft:860,bonusSqft:660,lotAcres:1.46,beds:2,baths:1,bonusLegal:'Unverified',bonusNotes:'Finished, permanently heated bonus room above powered garage with separate exterior deck access.',purchasePrice:'',purchaseDate:'',
sources:seededSources,comps:seededComps,projects:seededProjects,risks:seededRisks,marketHistory:[],saleHistory:[],savedScenarios:[],
valueBasis:'avm',manualValue:'',growthLow:1,growthBase:2.75,growthHigh:4.5,inflationRate:2.5,realDollars:false,sellCost:7,repairReserve:10000,
originalLoan:'',loanRate:'',loanTerm:30,loanStart:'',actualBalance:'',actualBalanceAsOf:'',totalMonthly:'',nextPaymentDue:'',mortgageLoanType:'',mortgageOriginalPayoffDate:'',mortgageEstimatedPayoffDate:'',mortgageExtraPaymentsSavings:'',mortgageMonthsReduced:'',
marketYoy:-1.6,marketForecast:0.4,inventoryCount:314,inventoryYoy:23.9,daysOnMarket:64,marketRate:7.28,saleToList:98.5,priceCutShare:35,
equityTarget:400000,replacementPrice:700000,replacementRate:7.28,replacementTerm:30,replacementGrowth:2.75,staySellHorizon:5,
alertValueTarget:700000,alertMarketScore:75,alertNetTarget:400000};
function normalizeProject(p){return {...{tier:'medium',score:3,type:'Custom',budget:0,valueAdd:0,status:'Idea',actual:0,permit:'Maybe',selected:false,why:''},...p}}
function normalizeComp(c){return {...{salePrice:0,saleDate:'',sqft:0,acres:'',beds:'',baths:'',quality:'okay',adjustment:0,use:true,notes:''},...c}}
function load(){let x=null;try{x=JSON.parse(localStorage.getItem(STORAGE))}catch(e){};if(!x){try{x=JSON.parse(localStorage.getItem(LEGACY))}catch(e){}}const base=clone(defaults);if(!x)return base;const out={...base,...x};out.sources=x.sources||base.sources;out.comps=(x.comps||base.comps).map(normalizeComp);out.projects=(x.projects||base.projects).map(normalizeProject);out.risks=x.risks||base.risks;out.marketHistory=x.marketHistory||[];out.saleHistory=x.saleHistory||[];out.savedScenarios=x.savedScenarios||[];return out}
let state=load();
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function median(a){const x=[...a].filter(Number.isFinite).sort((p,q)=>p-q);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function avmValue(){return median(state.sources.filter(s=>s.inBlend&&Number(s.value)>0).map(s=>Number(s.value)))}
function compWeight(q){return q==='strong'?3:q==='weak'?1:2}
function compEstimate(){const used=state.comps.filter(c=>c.use&&Number(c.salePrice)>0);if(!used.length)return 0;let sum=0,w=0;used.forEach(c=>{const implied=Number(c.salePrice)*(1+Number(c.adjustment||0)/100),cw=compWeight(c.quality);sum+=implied*cw;w+=cw});return w?sum/w:0}
function decisionValue(){if(state.valueBasis==='manual'&&Number(state.manualValue)>0)return Number(state.manualValue);if(state.valueBasis==='comps'&&compEstimate()>0)return compEstimate();return avmValue()}
function confidence(){const vals=state.sources.filter(s=>s.inBlend&&Number(s.value)>0).map(s=>Number(s.value));const mid=median(vals),spread=vals.length>1?(Math.max(...vals)-Math.min(...vals))/(mid||1):1;let score=0;score+=spread<=.08?40:spread<=.15?30:spread<=.25?20:10;const comps=state.comps.filter(c=>c.use&&Number(c.salePrice)>0);const strong=comps.filter(c=>c.quality==='strong').length;score+=Math.min(35,comps.length*4+strong*5);score+=vals.length>=3?10:vals.length===2?6:2;score+=state.bonusLegal==='Verified'?15:state.bonusLegal==='Unverified'?8:4;return clamp(Math.round(score),0,100)}
function confidenceLabel(s){return s>=75?'High':s>=50?'Medium':'Low'}
function payment(P,rate,years){P=Number(P)||0;const n=(Number(years)||30)*12,r=(Number(rate)||0)/1200;if(!P)return 0;if(!r)return P/n;return P*r/(1-Math.pow(1+r,-n))}
function monthsBetween(start,end){if(!start)return 0;const d=new Date(start+'T12:00:00');if(Number.isNaN(d.getTime()))return 0;let m=(end.getFullYear()-d.getFullYear())*12+(end.getMonth()-d.getMonth());if(end.getDate()<d.getDate())m--;return Math.max(0,m)}
function loanBalanceAt(date){
  const target=date instanceof Date?date:new Date(date),actual=Number(state.actualBalance)||0,rate=Number(state.loanRate)||0,years=Number(state.loanTerm)||30;
  if(actual>0){
    const asOf=state.actualBalanceAsOf||today(),asOfDate=new Date(asOf+'T12:00:00');
    if(!Number.isNaN(asOfDate.getTime())&&target>=asOfDate){
      const k=monthsBetween(asOf,target);
      if(k<=0)return actual;
      const r=rate/1200,scheduledPI=payment(Number(state.originalLoan)||actual,rate,years);
      if(!r)return Math.max(0,actual-scheduledPI*k);
      return Math.max(0,actual*Math.pow(1+r,k)-scheduledPI*((Math.pow(1+r,k)-1)/r));
    }
  }
  const P=Number(state.originalLoan)||0,n=years*12,r=rate/1200;
  if(!P||!state.loanStart)return actual;
  const k=Math.min(n,monthsBetween(state.loanStart,target));
  if(k>=n)return 0;
  if(!r)return Math.max(0,P-(P/n)*k);
  const pay=payment(P,rate,years);
  return Math.max(0,P*Math.pow(1+r,k)-pay*((Math.pow(1+r,k)-1)/r));
}
function currentBalance(){return Number(state.actualBalance)>0?Number(state.actualBalance):loanBalanceAt(new Date())}
function saleNet(value=decisionValue(),date=new Date()){return Math.max(0,Number(value)-loanBalanceAt(date)-Number(value)*(Number(state.sellCost)/100)-Number(state.repairReserve||0))}
function displayFuture(n,years){return state.realDollars?Number(n)/Math.pow(1+Number(state.inflationRate)/100,years):Number(n)}
function futurePoint(y){const base=decisionValue(),now=new Date(),d=new Date(now);d.setFullYear(now.getFullYear()+y);const low=base*Math.pow(1+Number(state.growthLow)/100,y),mid=base*Math.pow(1+Number(state.growthBase)/100,y),high=base*Math.pow(1+Number(state.growthHigh)/100,y),bal=loanBalanceAt(d),net=mid-bal-mid*(Number(state.sellCost)/100)-Number(state.repairReserve||0);return {year:now.getFullYear()+y,date:d,low:displayFuture(low,y),value:displayFuture(mid,y),high:displayFuture(high,y),nominal:mid,bal,net:displayFuture(net,y)}}
function currentEquity(){return decisionValue()-currentBalance()}
function selectedProjectTotals(){const list=state.projects.filter(p=>p.selected);return {cost:list.reduce((s,p)=>s+Number(p.budget||0),0),valueAdd:list.reduce((s,p)=>s+Number(p.valueAdd||0),0),list}}
function postRenoValue(){const t=selectedProjectTotals();return decisionValue()+t.valueAdd}
function marketScore(){const f=[
{name:'Price momentum',weight:20,score:clamp((Number(state.marketYoy)+5)/10,0,1)*20,good:Number(state.marketYoy)>0,why:`Local values ${pct(state.marketYoy)} year over year.`},
{name:'1-year forecast',weight:15,score:clamp((Number(state.marketForecast)+2)/5,0,1)*15,good:Number(state.marketForecast)>1,why:`Near-term forecast ${pct(state.marketForecast)}.`},
{name:'Inventory pressure',weight:20,score:clamp((20-Number(state.inventoryYoy))/40,0,1)*20,good:Number(state.inventoryYoy)<0,why:`Active inventory ${pct(state.inventoryYoy)} year over year.`},
{name:'Days on market',weight:15,score:clamp((90-Number(state.daysOnMarket))/70,0,1)*15,good:Number(state.daysOnMarket)<45,why:`Median ${Math.round(Number(state.daysOnMarket))} days on market.`},
{name:'Mortgage rates',weight:15,score:clamp((8-Number(state.marketRate))/4,0,1)*15,good:Number(state.marketRate)<6,why:`Buyer financing around ${Number(state.marketRate).toFixed(2)}%.`},
{name:'Sale-to-list',weight:10,score:clamp((Number(state.saleToList)-95)/7,0,1)*10,good:Number(state.saleToList)>=100,why:`Sale-to-list ratio ${Number(state.saleToList).toFixed(1)}%.`},
{name:'Price cuts',weight:5,score:clamp((50-Number(state.priceCutShare))/35,0,1)*5,good:Number(state.priceCutShare)<25,why:`Listings with price cuts: ${Number(state.priceCutShare).toFixed(0)}%.`}];return {f,total:Math.round(f.reduce((s,x)=>s+x.score,0))}}
function replacementCalc(){const sale= saleNet(),price=Number(state.replacementPrice)||0,down=Math.min(price,sale),loan=Math.max(0,price-down),pi=payment(loan,state.replacementRate,state.replacementTerm);return {sale,price,down,loan,pi}}
function financialScore(){const val=decisionValue(),bal=currentBalance(),net=saleNet(),target=Math.max(1,Number(state.equityTarget)||1),equityRatio=val?Math.max(0,(val-bal)/val):0,rep=replacementCalc(),currentPI=payment(state.originalLoan,state.loanRate,state.loanTerm),rateGap=(Number(state.marketRate)||0)-(Number(state.loanRate)||0);const f=[];f.push({name:'Net proceeds target',weight:35,score:clamp(net/target,0,1)*35,why:`Estimated cash after sale ${money(net)} vs target ${money(target)}.`});f.push({name:'Equity position',weight:25,score:clamp(equityRatio/.65,0,1)*25,why:`Gross equity ratio about ${(equityRatio*100).toFixed(0)}%.`});let payScore=10;if(currentPI>0&&rep.pi>0)payScore=clamp(1-(rep.pi-currentPI)/(currentPI*.8),0,1)*20;else payScore=10;f.push({name:'Replacement payment',weight:20,score:payScore,why:currentPI>0?`Current P&I ${money(currentPI)} vs replacement P&I ${money(rep.pi)}.`:'Add mortgage details for a stronger comparison.'});let lock=10;if(Number(state.loanRate)>0)lock=clamp(1-rateGap/4,0,1)*20;f.push({name:'Rate lock-in',weight:20,score:lock,why:Number(state.loanRate)>0?`Existing rate ${Number(state.loanRate).toFixed(2)}% vs market ${Number(state.marketRate).toFixed(2)}%.`:'Add current mortgage rate for this factor.'});return {f,total:Math.round(f.reduce((s,x)=>s+x.score,0))}}
function combinedSellScore(){const m=marketScore().total,f=financialScore().total;return Math.round(m*.55+f*.45)}
function sellerWindow(){return marketScore().total>=75&&financialScore().total>=65}
function bind(id,key,render=renderAll){const el=$(id);if(!el)return;el.value=state[key]??'';if(el.type==='checkbox')el.checked=!!state[key];el.addEventListener('change',()=>{state[key]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?'':Number(el.value)):el.value;save();render()})}
function setText(id,text){const el=$(id);if(el)el.textContent=text}
function renderHeader(){setText('appTitle',state.propertyName||'Juniper Home Tracker');setText('appSubtitle',state.privateAddress?`${state.privateAddress} · stored only on this device`:state.locationLabel||'Private local property tracker')}
function renderOverview(){const v=decisionValue(),avm=avmValue(),comp=compEstimate(),c=confidence(),bal=currentBalance(),net=saleNet();setText('decisionValue',money(v));setText('valueBasisLabel',state.valueBasis==='avm'?'AVM median':state.valueBasis==='comps'?'Comp-weighted estimate':'Manual value');setText('avmValue',money(avm));setText('compValue',comp?money(comp):'—');setText('loanBalance',bal?money(bal):'Add mortgage');setText('grossEquity',bal?money(v-bal):'—');setText('netToday',bal||Number(state.originalLoan)?money(net):'Add mortgage');setText('confidenceNum',c);$('confidenceDial').style.setProperty('--score',c);setText('confidenceLabel',`${confidenceLabel(c)} confidence`);const vals=state.sources.filter(s=>s.inBlend&&Number(s.value)>0).map(s=>Number(s.value));setText('confidenceExplain',vals.length>1?`AVM spread ${money(Math.min(...vals))}–${money(Math.max(...vals))}; ${state.comps.filter(x=>x.use).length} active comps; bonus-space legal status: ${state.bonusLegal}.`:'Add more valuation sources and comps to improve confidence.');renderSources();renderProjection();renderAlerts()}
function renderSources(){const box=$('sourceList');if(!box)return;box.innerHTML='';state.sources.forEach(s=>{const d=document.createElement('div');d.className='source';d.innerHTML=`<div><strong>${esc(s.name)}</strong><small>${s.inBlend?'Included in AVM median':'Cross-check only'} · ${esc(s.date||'')}</small></div><input type="number" step="100" value="${Number(s.value)||0}" aria-label="${esc(s.name)} value"><a href="${esc(s.url||'#')}" target="_blank">${s.url?'Open':'—'}</a>`;d.querySelector('input').addEventListener('change',e=>{s.value=Number(e.target.value)||0;save();renderAll()});box.appendChild(d)})}
function renderProjection(){const body=$('projectionBody');if(!body)return;body.innerHTML=[0,5,10,15,20].map(y=>{const p=futurePoint(y);return `<tr><td>${p.year}</td><td>${money(p.low)}</td><td><strong>${money(p.value)}</strong></td><td>${money(p.high)}</td><td>${p.bal?money(p.bal):'—'}</td><td class="money-positive">${money(p.net)}</td></tr>`}).join('');setText('dollarMode',state.realDollars?`Inflation-adjusted to today's dollars at ${Number(state.inflationRate).toFixed(1)}% inflation.`:'Nominal future dollars.')}
function renderComps(){const box=$('compList');if(!box)return;box.innerHTML='';state.comps.forEach(c=>{const implied=Number(c.salePrice)*(1+Number(c.adjustment||0)/100),d=document.createElement('div');d.className='compCard';d.innerHTML=`<div class="compHead"><div><strong>${esc(c.address||'Unnamed comp')}</strong><div class="compMeta">${c.saleDate?esc(c.saleDate)+' · ':''}${c.sqft?Number(c.sqft).toLocaleString()+' sf · ':''}${c.beds||'—'}/${c.baths||'—'} · ${c.acres?c.acres+' ac':''}</div></div><label class="check"><input type="checkbox" ${c.use?'checked':''}> use</label></div><div class="compGrid"><label><span class="form-label">Sale price</span><input data-k="salePrice" type="number" value="${c.salePrice||''}"></label><label><span class="form-label">Sq ft</span><input data-k="sqft" type="number" value="${c.sqft||''}"></label><label><span class="form-label">Quality</span><select data-k="quality"><option ${c.quality==='strong'?'selected':''}>strong</option><option ${c.quality==='okay'?'selected':''}>okay</option><option ${c.quality==='weak'?'selected':''}>weak</option></select></label><label><span class="form-label">Adjustment %</span><input data-k="adjustment" type="number" step="1" value="${c.adjustment||0}"></label></div><div class="row wrap" style="margin-top:8px"><span class="badge ${c.quality==='strong'?'good':c.quality==='weak'?'bad':'warn'}">${esc(c.quality)}</span><span class="badge blue">$/sf ${c.sqft?money(c.salePrice/c.sqft):'—'}</span><span class="badge">implied ${money(implied)}</span></div><label style="display:block;margin-top:8px"><span class="form-label">Notes</span><textarea data-k="notes">${esc(c.notes)}</textarea></label><button class="btn small danger" data-delete>Remove</button>`;d.querySelector('input[type="checkbox"]').addEventListener('change',e=>{c.use=e.target.checked;save();renderAll()});d.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('change',()=>{const k=el.dataset.k;c[k]=el.type==='number'?(el.value===''?'':Number(el.value)):el.value;save();renderAll()}));d.querySelector('[data-delete]').addEventListener('click',()=>{state.comps=state.comps.filter(x=>x.id!==c.id);save();renderAll()});box.appendChild(d)});setText('compEstimate',compEstimate()?money(compEstimate()):'No active comps');setText('compCount',`${state.comps.filter(c=>c.use).length} active comps`)}
function addComp(){const address=$('newCompAddress').value.trim();if(!address)return;state.comps.push(normalizeComp({id:'c'+Date.now(),address,salePrice:Number($('newCompPrice').value)||0,saleDate:$('newCompDate').value,sqft:Number($('newCompSqft').value)||0,quality:'okay',use:true,notes:''}));['newCompAddress','newCompPrice','newCompDate','newCompSqft'].forEach(id=>$(id).value='');save();renderAll()}
function renderRenovations(){const box=$('projectList');if(!box)return;const filter=$('projectFilter').value||'all';box.innerHTML='';state.projects.filter(p=>filter==='all'||p.tier===filter).sort((a,b)=>b.score-a.score).forEach(p=>{const d=document.createElement('div');d.className='project';d.innerHTML=`<div class="projectHead"><div><label class="check"><input class="selectProject" type="checkbox" ${p.selected?'checked':''}><strong>${esc(p.name)}</strong></label><div class="badgeRow"><span class="badge">${esc(p.tier)}</span><span class="badge ${p.score>=5?'good':''}">leverage ${p.score}/5</span><span class="badge blue">${esc(p.type)}</span></div></div><strong>${money(p.budget)}</strong></div><p class="tiny">${esc(p.why)}</p><div class="projectGrid"><label><span class="form-label">Status</span><select data-k="status">${['Idea','Researching','Quoted','Permitted','Scheduled','Underway','Complete'].map(x=>`<option ${p.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span class="form-label">Budget</span><input data-k="budget" type="number" value="${p.budget||0}"></label><label><span class="form-label">Actual spent</span><input data-k="actual" type="number" value="${p.actual||0}"></label><label><span class="form-label">Planning value add</span><input data-k="valueAdd" type="number" value="${p.valueAdd||0}"></label></div><div class="tiny" style="margin-top:7px">Permit expectation: ${esc(p.permit)} · Value-add number is editable planning input, not an appraisal.</div>`;d.querySelector('.selectProject').addEventListener('change',e=>{p.selected=e.target.checked;save();renderAll()});d.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('change',()=>{p[el.dataset.k]=el.type==='number'?Number(el.value)||0:el.value;save();renderAll()}));box.appendChild(d)});renderRenoScenario()}
function renderRenoScenario(){const t=selectedProjectTotals(),base=decisionValue(),post=base+t.valueAdd;setText('renoBase',money(base));setText('renoCost',money(t.cost));setText('renoValueAdd',money(t.valueAdd));setText('renoAfter',money(post));setText('renoNetImpact',money(t.valueAdd-t.cost));setText('renoCount',`${t.list.length} projects selected`)}
function saveScenario(){const t=selectedProjectTotals();if(!t.list.length)return;const name=prompt('Scenario name?','Selected renovation plan');if(!name)return;state.savedScenarios.push({id:'s'+Date.now(),name,created:today(),base:decisionValue(),cost:t.cost,valueAdd:t.valueAdd,projects:t.list.map(p=>p.name)});save();renderSavedScenarios()}
function renderSavedScenarios(){const box=$('savedScenarioList');if(!box)return;if(!state.savedScenarios.length){box.innerHTML='<div class="note">No saved renovation scenarios yet.</div>';return}box.innerHTML=state.savedScenarios.map(s=>`<div class="scenarioCard"><div class="row"><div class="grow"><strong>${esc(s.name)}</strong><div class="tiny">${esc(s.created)} · ${s.projects.length} projects</div></div><button class="btn small danger" data-id="${s.id}">Remove</button></div><div class="badgeRow"><span class="badge">cost ${money(s.cost)}</span><span class="badge blue">value add ${money(s.valueAdd)}</span><span class="badge good">post-reno ${money(s.base+s.valueAdd)}</span></div><div class="tiny" style="margin-top:7px">${esc(s.projects.join(' · '))}</div></div>`).join('');box.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>{state.savedScenarios=state.savedScenarios.filter(s=>s.id!==b.dataset.id);save();renderSavedScenarios()}))}
function renderSellStay(){const rep=replacementCalc(),v=decisionValue(),net=saleNet(),currentPI=payment(state.originalLoan,state.loanRate,state.loanTerm),h=Number(state.staySellHorizon)||5;const stayFuture=v*Math.pow(1+Number(state.growthBase)/100,h),d=new Date();d.setFullYear(d.getFullYear()+h);const stayEq=stayFuture-loanBalanceAt(d);const repFuture=rep.price*Math.pow(1+Number(state.replacementGrowth)/100,h);const repLoanBal=amortizedBalance(rep.loan,state.replacementRate,state.replacementTerm,h*12);const repEq=repFuture-repLoanBal;setText('sellCash',money(net));setText('replacementDown',money(rep.down));setText('replacementLoan',money(rep.loan));setText('replacementPI',money(rep.pi));setText('currentPI',currentPI?money(currentPI):'Add mortgage');setText('paymentDelta',currentPI?money(rep.pi-currentPI):'—');setText('stayFutureEquity',money(stayEq));setText('moveFutureEquity',money(repEq));setText('horizonLabel',`${h}-year rough comparison`);const fin=financialScore();setText('financialScore',fin.total);$('financialDial').style.setProperty('--score',fin.total);setText('financialLabel',fin.total>=70?'Strong exit position':fin.total>=50?'Moderate exit position':'Weak exit position');$('financialFactors').innerHTML=fin.f.map(f=>factorRow(f)).join('')}
function amortizedBalance(P,rate,term,months){P=Number(P)||0;if(!P)return 0;const n=(Number(term)||30)*12,r=(Number(rate)||0)/1200,k=Math.min(n,months);if(!r)return Math.max(0,P-(P/n)*k);const pay=payment(P,rate,term);return Math.max(0,P*Math.pow(1+r,k)-pay*((Math.pow(1+r,k)-1)/r))}
function factorRow(f){return `<div class="scoreLine"><span title="${esc(f.why)}">${esc(f.name)}</span><div class="bar"><div class="fill" style="width:${clamp(f.score/f.weight*100,0,100)}%"></div></div><strong>${Math.round(f.score)}/${f.weight}</strong></div>`}
function renderMarket(){const m=marketScore(),f=financialScore(),combined=combinedSellScore(),win=sellerWindow();setText('marketScore',m.total);$('marketDial').style.setProperty('--score',m.total);setText('marketLabel',m.total>=75?'Strong seller market':m.total>=60?'Seller-leaning':m.total>=40?'Mixed market':'Buyer-favored');setText('combinedScore',combined);setText('sellWindowStatus',win?'SELL WINDOW':'WATCH / HOLD');$('sellWindowStatus').className='bigStatus '+(win?'money-positive':combined>=55?'money-warning':'money-negative');$('marketFactors').innerHTML=m.f.map(factorRow).join('');const positives=m.f.filter(x=>x.good).map(x=>x.why),negatives=m.f.filter(x=>!x.good).sort((a,b)=>a.score/a.weight-b.score/b.weight).slice(0,3).map(x=>x.why);$('sellerWhy').innerHTML=`<strong>${win?'Why this is green':'What is holding the score back'}</strong><div class="tiny" style="margin-top:6px">${esc((win?positives:negatives).join(' · ')||'Keep collecting market snapshots to improve the signal.')}</div>`;renderTimingChart();renderSnapshots()}
function renderTimingChart(){const svg=$('timingChart');if(!svg)return;const W=760,H=360,L=64,R=22,T=34,B=50;const future=[0,5,10,15,20].map(futurePoint),hist=state.marketHistory.map(h=>({year:new Date(h.date+'T12:00:00').getFullYear()+new Date(h.date+'T12:00:00').getMonth()/12,value:Number(h.value),score:Number(h.marketScore||h.score||0),snapshot:true}));const sales=state.saleHistory.filter(x=>Number(x.price)>0&&x.date).map(x=>({year:new Date(x.date+'T12:00:00').getFullYear()+new Date(x.date+'T12:00:00').getMonth()/12,value:Number(x.price),sale:true}));const now=new Date(),nowX=now.getFullYear()+now.getMonth()/12,core=[...sales,...hist,{year:nowX,value:decisionValue(),current:true},...future.slice(1).map(p=>({year:p.year,value:p.value,future:true,net:p.net}))].sort((a,b)=>a.year-b.year);if(!core.length)return;const minX=Math.min(...core.map(p=>p.year),now.getFullYear()-5),maxX=Math.max(...core.map(p=>p.year));const values=[...core.map(p=>p.value),...future.map(p=>p.low),...future.map(p=>p.high)].filter(x=>x>0),minY=Math.min(...values)*.9,maxY=Math.max(...values)*1.08;const x=v=>L+(v-minX)/(maxX-minX||1)*(W-L-R),y=v=>T+(maxY-v)/(maxY-minY||1)*(H-T-B);let out='';for(let i=0;i<=4;i++){const val=minY+(maxY-minY)*i/4,yy=y(val);out+=`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" stroke="#29402f"/><text x="${L-7}" y="${yy+4}" text-anchor="end" fill="#8fa08f" font-size="11">${Math.round(val/1000)}k</text>`}const band=future.map(p=>`${x(p.year)},${y(p.high)}`).join(' ')+' '+future.slice().reverse().map(p=>`${x(p.year)},${y(p.low)}`).join(' ');out+=`<polygon points="${band}" fill="#6b8793" opacity=".16"/>`;const path=[{year:nowX,value:decisionValue()},...future.slice(1)].map((p,i)=>`${i?'L':'M'} ${x(p.year)} ${y(p.value)}`).join(' ');out+=`<path d="${path}" fill="none" stroke="#9ac69d" stroke-width="4"/>`;core.forEach(p=>{const fill=p.current?'#f4f1e8':p.sale?'#d3ae62':p.snapshot?(p.score>=75?'#6ea672':'#7ba6ba'):'#9ac69d';out+=`<circle cx="${x(p.year)}" cy="${y(p.value)}" r="${p.current?7:5}" fill="${fill}" stroke="#0d1510" stroke-width="3"/>`;if(p.current)out+=`<text x="${x(p.year)}" y="${y(p.value)-14}" text-anchor="middle" fill="#f4f1e8" font-size="11" font-weight="800">${money(p.value)}</text>`;if(p.snapshot&&p.score>=75)out+=`<text x="${x(p.year)}" y="${Math.max(18,y(p.value)-28)}" text-anchor="middle" fill="#9ac69d" font-size="10" font-weight="900">SELL WINDOW</text>`});future.slice(1).forEach(p=>{if(p.net>=Number(state.equityTarget)){const xx=x(p.year),yy=y(p.value);out+=`<polygon points="${xx},${yy-10} ${xx-7},${yy-24} ${xx+7},${yy-24}" fill="#6ea672"/><text x="${xx}" y="${Math.max(18,yy-31)}" text-anchor="middle" fill="#9ac69d" font-size="10" font-weight="800">WATCH</text>`}});for(let yr=Math.ceil(minX/5)*5;yr<=maxX;yr+=5)out+=`<text x="${x(yr)}" y="${H-18}" text-anchor="middle" fill="#8fa08f" font-size="11">${yr}</text>`;svg.innerHTML=out}
function saveSnapshot(){const snap={date:today(),value:Math.round(decisionValue()),marketScore:marketScore().total,financialScore:financialScore().total,marketYoy:Number(state.marketYoy),forecast:Number(state.marketForecast),inventoryYoy:Number(state.inventoryYoy),dom:Number(state.daysOnMarket),rate:Number(state.marketRate),saleToList:Number(state.saleToList),priceCutShare:Number(state.priceCutShare)};const i=state.marketHistory.findIndex(x=>x.date===snap.date);if(i>=0)state.marketHistory[i]=snap;else state.marketHistory.push(snap);state.marketHistory.sort((a,b)=>a.date.localeCompare(b.date));save();renderAll();checkBrowserAlerts()}
function renderSnapshots(){const box=$('snapshotList');if(!box)return;if(!state.marketHistory.length){box.innerHTML='<div class="note">No snapshots yet. Monthly or quarterly is enough to build a useful local cycle history.</div>';return}box.innerHTML=state.marketHistory.slice().reverse().map((h,i)=>`<div class="history-item"><span><strong>${esc(h.date)}</strong><br><small>${money(h.value)}</small></span><span>Market ${h.marketScore??h.score} / Financial ${h.financialScore??'—'}</span><button class="btn small danger" data-i="${state.marketHistory.length-1-i}">×</button></div>`).join('');box.querySelectorAll('[data-i]').forEach(b=>b.addEventListener('click',()=>{state.marketHistory.splice(Number(b.dataset.i),1);save();renderAll()}))}
function renderProperty(){['propertyName','privateAddress','locationLabel','primarySqft','bonusSqft','lotAcres','beds','baths','bonusLegal','bonusNotes','purchasePrice','purchaseDate','originalLoan','loanRate','loanTerm','loanStart','actualBalance','totalMonthly'].forEach(id=>{const el=$(id);if(el&&document.activeElement!==el)el.value=state[id]??''});setText('spaceSummary',`${Number(state.primarySqft)||0} sf primary + ~${Number(state.bonusSqft)||0} sf additional garage/bonus area · ${state.beds||'—'} bed / ${state.baths||'—'} bath · ${state.lotAcres||'—'} acres`);renderRisks();renderSaleHistory()}
function renderRisks(){const box=$('riskList');if(!box)return;box.innerHTML=state.risks.map(r=>`<div class="risk ${esc(r.status)}"><div class="riskHead"><strong><span class="statusDot"></span>${esc(r.name)}</strong><select data-id="${r.id}" style="max-width:110px"><option value="low" ${r.status==='low'?'selected':''}>low</option><option value="watch" ${r.status==='watch'?'selected':''}>watch</option><option value="action" ${r.status==='action'?'selected':''}>action</option></select></div><div class="tiny" style="margin-top:7px">${esc(r.notes)}</div></div>`).join('');box.querySelectorAll('select').forEach(s=>s.addEventListener('change',()=>{const r=state.risks.find(x=>x.id===s.dataset.id);r.status=s.value;save();renderAll()}));const action=state.risks.filter(r=>r.status==='action').length,watch=state.risks.filter(r=>r.status==='watch').length;setText('riskSummary',action?`${action} action items`:watch?`${watch} items to watch`:'No flagged risks')}
function addSaleHistory(){const date=$('saleHistDate').value,price=Number($('saleHistPrice').value)||0,note=$('saleHistNote').value.trim();if(!date||!price)return;state.saleHistory.push({id:'h'+Date.now(),date,price,note});state.saleHistory.sort((a,b)=>a.date.localeCompare(b.date));$('saleHistDate').value='';$('saleHistPrice').value='';$('saleHistNote').value='';save();renderAll()}
function renderSaleHistory(){const box=$('saleHistoryList');if(!box)return;if(!state.saleHistory.length){box.innerHTML='<div class="note">Add prior transactions here. Keep distressed or unusual sales labeled so they are context, not blindly treated as trend data.</div>';return}box.innerHTML=state.saleHistory.slice().reverse().map(h=>`<div class="history-item"><span><strong>${esc(h.date)}</strong><br><small>${esc(h.note||'Recorded sale')}</small></span><span>${money(h.price)}</span><button class="btn small danger" data-id="${h.id}">×</button></div>`).join('');box.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>{state.saleHistory=state.saleHistory.filter(h=>h.id!==b.dataset.id);save();renderAll()}))}
function renderAlerts(){const box=$('alertList');if(!box)return;const v=decisionValue(),m=marketScore().total,n=saleNet();const items=[['Value target',v,Number(state.alertValueTarget),money],['Market score',m,Number(state.alertMarketScore),x=>`${Math.round(x)}/100`],['Net proceeds',n,Number(state.alertNetTarget),money]];box.innerHTML=items.map(([name,cur,target,fmt])=>`<div class="alertItem"><span><strong>${name}</strong><div class="tiny">Current ${fmt(cur)} · target ${fmt(target)}</div></span><span class="badge ${cur>=target?'good':'warn'}">${cur>=target?'TRIGGERED':`${fmt(Math.max(0,target-cur))} away`}</span></div>`).join('')}
async function enableNotifications(){if(!('Notification'in window)){alert('Browser notifications are not supported here.');return}const p=await Notification.requestPermission();alert(p==='granted'?'Browser alerts enabled. The app will notify when it is open and a threshold is crossed.':'Notification permission was not granted.')}
function checkBrowserAlerts(){if(!('Notification'in window)||Notification.permission!=='granted')return;const hits=[];if(decisionValue()>=Number(state.alertValueTarget))hits.push(`Home value reached ${money(decisionValue())}`);if(marketScore().total>=Number(state.alertMarketScore))hits.push(`Market score reached ${marketScore().total}/100`);if(saleNet()>=Number(state.alertNetTarget))hits.push(`Estimated net proceeds reached ${money(saleNet())}`);if(hits.length)new Notification('Juniper Home Tracker',{body:hits.join(' · ')})}
function addProject(){const name=$('newProjectName').value.trim();if(!name)return;state.projects.push(normalizeProject({id:'u'+Date.now(),name,tier:$('newProjectTier').value,score:Number($('newProjectScore').value)||3,budget:Number($('newProjectBudget').value)||0,valueAdd:Number($('newProjectValueAdd').value)||0,why:$('newProjectWhy').value.trim(),type:'Custom'}));['newProjectName','newProjectBudget','newProjectValueAdd','newProjectWhy'].forEach(id=>$(id).value='');save();renderAll()}
function resetSources(){state.sources=clone(seededSources);save();renderAll()}
function renderAll(){renderHeader();renderOverview();renderComps();renderRenovations();renderSavedScenarios();renderSellStay();renderMarket();renderProperty()}
function init(){document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(btn.dataset.tab).classList.add('active');renderAll()}));
['valueBasis','manualValue','growthLow','growthBase','growthHigh','inflationRate','realDollars','sellCost','repairReserve','equityTarget','replacementPrice','replacementRate','replacementTerm','replacementGrowth','staySellHorizon','marketYoy','marketForecast','inventoryCount','inventoryYoy','daysOnMarket','marketRate','saleToList','priceCutShare','alertValueTarget','alertMarketScore','alertNetTarget','propertyName','privateAddress','locationLabel','primarySqft','bonusSqft','lotAcres','beds','baths','bonusLegal','bonusNotes','purchasePrice','purchaseDate','originalLoan','loanRate','loanTerm','loanStart','actualBalance','totalMonthly'].forEach(id=>bind(id,id));
$('addComp').addEventListener('click',addComp);$('projectFilter').addEventListener('change',renderRenovations);$('addProject').addEventListener('click',addProject);$('saveScenario').addEventListener('click',saveScenario);$('saveSnapshot').addEventListener('click',saveSnapshot);$('addSaleHistory').addEventListener('click',addSaleHistory);$('resetSources').addEventListener('click',resetSources);$('enableNotifications').addEventListener('click',enableNotifications);renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);